import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, } from "next/font/google";
import { MyProvider } from "@/context/myProducts";



const montserrat = Montserrat({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MyProvider>
      <html lang="pt-br">
        <body
          className={montserrat.className}
        >
          {children}
        </body>
      </html>
    </MyProvider>
  );
}
